project_name: ImagineDriving

PROJ_DIR: null      # null: $(cwd)
CACHE_DIR: null     # null: $(PROJ_DIR)/.cache

datasets:
  source_images:
    dataset: pandaset
    path: "/proj/adas-data/data/pandaset"
    data_getters:
      rgb:
        camera: "front_camera"
        height: 1080
        width: 1920

      meta: {}

    data_tree: 
      pandaset: 
        001-003: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]

experiments:
  base-0.1:
    model_config_params:
      model_name: sdxlbase
      base_model_id: "stabilityai/stable-diffusion-xl-base-1.0"

    model_forward_params: 
      base_strength: 0.1
      base_num_steps: 50

  base-0.2:
    model_config_params:
      model_name: sdxlbase
      base_model_id: "stabilityai/stable-diffusion-xl-base-1.0"

    model_forward_params: 
      base_strength: 0.2
      base_num_steps: 50

  base-0.3:
    model_config_params:
      model_name: sdxlbase
      base_model_id: "stabilityai/stable-diffusion-xl-base-1.0"

    model_forward_params: 
      base_strength: 0.3
      base_num_steps: 50


  base-0.4:
    model_config_params:
      model_name: sdxlbase
      base_model_id: "stabilityai/stable-diffusion-xl-base-1.0"

    model_forward_params: 
      base_strength: 0.4
      base_num_steps: 50

  base-0.5:
    model_config_params:
      model_name: sdxlbase
      base_model_id: "stabilityai/stable-diffusion-xl-base-1.0"

    model_forward_params: 
      base_strength: 0.5
      base_num_steps: 50

output_dir: /proj/nlp4adas/master-thesis-shared/output/param_sweep