project_name: ImagineDriving

project_dir: null      # null: $(cwd)
cache_dir: null     # null: $(PROJ_DIR)/.cache

datasets:
  train_data:
    dataset: pandaset
    path: "/staging/agp/datasets/pandaset"
    data_getters:
      rgb:
        camera: "front_camera"
      prompt: 
        type: static
        positive_prompt: ""
        negative_prompt: ""

      meta: {}

    data_tree: 
      pandaset: 
        001-124: "0::1"
        #001: "0::8"
        #001:
        #  - 01
          

  val_data: 
    dataset: pandaset
    path: "/staging/agp/datasets/pandaset"
    data_getters:
      rgb:
        camera: "front_camera"

      prompt: 
        type: static
        positive_prompt: ""
        negative_prompt: ""

      meta: {}

    data_tree: 
      pandaset: 
        139-158: "0::16"
        #101: "0::16"
        #001:
        # - 01
        # - 09


#model_id: "runwayml/stable-diffusion-v1-5"
model_id: stabilityai/stable-diffusion-2-1
revision: null
variant: null
max_train_samples: null
seed: 0
train_batch_size: 16
dataloader_num_workers: 8

max_grad_norm: 1.0
mixed_precision: null
lora_rank: 128

n_epochs: 500
val_freq: 1

train_noise_strength: 0.4

val_noise_num_steps: 50
val_noise_strength: 0.2

add_rgb_loss: True

learning_rate: 0.0003
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 0.00000001

#lr_scheduler: "constant"
#lr_warmup_steps: 1000

lr_scheduler: "cosine_with_restarts"
lr_warmup_steps: 1000
lr_scheduler_kwargs:
  num_cycles: 3

#center_crop: True
#flip_prob: 0

center_crop: False
flip_prob: 0.5

#crop_height: null
#crop_width: null
crop_height: 512
crop_width: 512
resize_factor: 1.0

image_height: 1080
image_width: 1920

output_dir: /staging/agp/masterthesis/nerf-thesis-shared/output/finetune/sd_v2_1
loggers: 
  - wandb
