FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

ARG CONDA_ENV_NAME="env-diffusion"
ENV CONDA_OVERRIDE_CUDA="11.3"

ENV PYTHONNOUSERSITE=True
## Set non-interactive to prevent asking for user inputs blocking image creation.
ENV DEBIAN_FRONTEND=noninteractive
## Set timezone as it is required by some packages.
ENV TZ=Europe/Berlin
## CUDA Home, required to find CUDA in some packages.
ENV CUDA_HOME="/usr/local/cuda"
ENV PATH=/opt/mambaforge/bin:$PATH

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    nano \
    wget \
    curl

#SHELL ["/bin/bash", "-c"]

# Mambaforge
RUN cd /tmp && \
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh" && \
    bash Mambaforge-$(uname)-$(uname -m).sh -fp /opt/mambaforge -b && \
    rm Mambaforge*sh

COPY environment.yml .
RUN mamba env create -n ${CONDA_ENV_NAME} -f environment.yml 
#RUN mamba create -n ${CONDA_ENV_NAME} python\>\=3.10 pytorch\>\=2.0.0 pytorch-gpu\>\=2.0.0 cudatoolkit\<\=11.4 -c conda-forge

# Create nonroot user, setup env
RUN useradd -m -d /home/user -g root -G sudo -u 1000 user
RUN usermod -aG sudo user
#User password
RUN echo "user:user" | chpasswd
# Ensure sudo group users are not asked for password
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
#Switch to new user and workdir
USER 1000
WORKDIR /home/user
# Add local user binary folder to Path variable
ENV PATH="${PATH}:/home/user/.local/bin"

RUN echo "source activate ${CONDA_ENV_NAME}" > ~/.bashrc
ENV CONDA_PREFIX /opt/mambaforge/envs/${CONDA_ENV_NAME}
ENV PATH ${CONDA_PREFIX}/bin:$PATH

#SHELL ["/bin/bash", "-c"]

WORKDIR /workspace
