FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04


# Set environment variables.
## Set non-interactive to prevent asking for user inputs blocking image creation.
ENV DEBIAN_FRONTEND=noninteractive
## Set timezone as it is required by some packages.
ENV TZ=Europe/Berlin
## CUDA Home, required to find CUDA in some packages.
ENV CUDA_HOME="/usr/local/cuda"

ENV PYTHONNOUSERSITE=True
## CUDA Home, required to find CUDA in some packages.
ENV PATH=/opt/mambaforge/bin:$PATH
ENV HF_HOME=/staging/agp/masterthesis/nerf-thesis-shared/cache/.cache
ENV MPLCONFIGDIR=/staging/agp/masterthesis/nerf-thesis-shared/cache/.cache

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    nano \
    wget \
    curl

# Mambaforge
RUN cd /tmp && \
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh" && \
    bash Mambaforge-$(uname)-$(uname -m).sh -fp /opt/mambaforge -b && \
    rm Mambaforge*sh

COPY environment.yml .
RUN mamba env update -f environment.yml 

SHELL ["/bin/bash", "-c"]

# Create nonroot user, setup env
RUN useradd -m -d /home/user -g root -G sudo -u 1000 user
RUN usermod -aG sudo user
# User password
RUN echo "user:user" | chpasswd
# Ensure sudo group users are not asked for password
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
#Switch to new user and workdir
USER 1000
WORKDIR /home/user
# Add local user binary folder to Path variable
ENV PATH="${PATH}:/home/user/.local/bin"

RUN echo "source activate env-diffusion" > ~/.bashrc
ENV PATH /opt/mambaforge/envs/env-diffusion/bin:$PATH
ENV CONDA_PREFIX /opt/mambaforge/envs/env-diffusion

SHELL ["/bin/bash", "-c"]

COPY requirements-base.txt .
COPY requirements-extra.txt .
RUN pip install --user -r requirements-base.txt
RUN pip install --user -r requirements-extra.txt

WORKDIR /workspace
