name: env-diffusion
channels:
  - conda-forge 
  - anaconda
  - pytorch 
  - nvidia 
dependencies:
  - python=3.11
  - pytorch=2.2.0
  - pytorch-cuda
  - nb_conda_kernels
  - jupyter
  - jupyterlab
  - pip