data_tree: 
  pandaset: 
    001-003: "*"

model_config_params:
  model_name: sdxlbase
  base_model_id: "stabilityai/stable-diffusion-xl-base-1.0"

model_forward_params: 
  base_strength: 0.1
  base_num_steps: 50